armor_detector_node:
  ros__parameters:
    target_color: "blue"
    brightness_threshold: 50
    light_min_area: 20
    always_publish_result: true
    light_max_ratio: 0.5 
    light_contour_min_solidity: 0.5
    light_color_detect_extend_ratio: 1.2
    light_max_angle_diff_: 10.0
    light_max_height_diff_ratio_: 0.3
    light_max_y_diff_ratio_: 0.2
    light_min_x_diff_ratio_: 0.5
    armor_max_aspect_ratio_: 4.0
    armor_min_aspect_ratio_: 1.0
    armor_big_armor_ratio: 2.0
